package com.example.restful_demo.model;

import org.springframework.stereotype.Component;

import java.util.Date;

@Component
public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.create_time
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.update_time
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.title
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.score
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    private Long score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.comment
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.is_deleted
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.create_time
     *
     * @return the value of book.create_time
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.create_time
     *
     * @param createTime the value for book.create_time
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.update_time
     *
     * @return the value of book.update_time
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.update_time
     *
     * @param updateTime the value for book.update_time
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.title
     *
     * @return the value of book.title
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.title
     *
     * @param title the value for book.title
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.score
     *
     * @return the value of book.score
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    public Long getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.score
     *
     * @param score the value for book.score
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    public void setScore(Long score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.comment
     *
     * @return the value of book.comment
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.comment
     *
     * @param comment the value for book.comment
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.is_deleted
     *
     * @return the value of book.is_deleted
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.is_deleted
     *
     * @param isDeleted the value for book.is_deleted
     *
     * @mbg.generated Sun Dec 01 12:33:30 CST 2019
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}